"use client";

import Image from "next/image";
import { useEffect, useState } from "react";
import { useWallet } from "@/components/WalletProvider";
import { authenticateProfileSession } from "@/lib/profile-auth-client";
import type { Discipline, Trick } from "@/lib/pvp";

type Session = { id:string; tokenId:number; discipline:Discipline; sequence:number; bankedScore:number; unbankedScore:number; multiplier:number; landedCount:number; status:string; targetTrickId:number; entryCost:number };
type OwnedGoon = { tokenId:number; name:string; discipline:Discipline; rarity:string; imageUrl:string };
type Started = { session:Session; accessKey:string; goon:OwnedGoon; tricks:Trick[]; target:Trick; obstacles:string[]; mastery:{entryCost:number;currentGrit:number;remainingGrit:number;chance:number;failedQualifiedRuns:number;guaranteeRun:number} };

export function TrickLineClient() {
  const { account, connect, signMessage, signProfileChallenge } = useWallet();
  const [owned,setOwned]=useState<OwnedGoon[]>([]), [tokenId,setTokenId]=useState<number|null>(null), [targetId,setTargetId]=useState<number|null>(null);
  const [career,setCareer]=useState<Record<string,unknown>|null>(null), [run,setRun]=useState<Started|null>(null), [trickId,setTrickId]=useState(0), [obstacle,setObstacle]=useState("");
  const [status,setStatus]=useState("Connect an owned Goon, choose a locked trick, and spend GRIT to begin a mastery run."), [busy,setBusy]=useState(false);
  const [attempt,setAttempt]=useState<{landed:boolean;trick:string;chance:number;roll:number;scoreDelta:number}|null>(null);

  useEffect(()=>{let live=true;if(!account){queueMicrotask(()=>{if(live)setOwned([])});return()=>{live=false};}Promise.all([fetch("/api/roster").then(r=>r.json()),fetch(`/api/ownership?wallet=${account}`).then(r=>r.json())]).then(([roster,ownership])=>{if(!live)return;const byId=new Map<number,Record<string,unknown>>((roster.athletes??[]).map((g:Record<string,unknown>)=>[Number(g.tokenId),g]));setOwned((ownership.tokenIds??[]).map((id:number)=>{const g=byId.get(Number(id))??{};return {tokenId:Number(id),name:String(g.name??`Gravity Goons #${id}`),discipline:String(g.discipline??"Skateboarding") as Discipline,rarity:String(g.rarity??"Common"),imageUrl:String(g.imageUrl??"/collection/base-concept.png")};}));});return()=>{live=false};},[account]);
  useEffect(()=>{let live=true;if(!tokenId){queueMicrotask(()=>{if(live)setCareer(null)});return()=>{live=false};}fetch(`/api/goons/${tokenId}/career`,{cache:"no-store"}).then(data=>data.json()).then(data=>{if(live)setCareer(data)}).catch(()=>{if(live)setCareer(null)});return()=>{live=false};},[tokenId]);
  const selected=owned.find(g=>g.tokenId===tokenId);
  const locked=(career?.lockedTricks as Trick[]|undefined)??[];
  const economy=(career?.economy as {grit_balance?:number;grit_reserved?:number}|undefined)??{};
  const spendable=Number(economy.grit_balance??0)-Number(economy.grit_reserved??0);
  const target=locked.find(t=>t.id===targetId);

  async function ensureAuth(){const wallet=account??await connect();if(!wallet)throw new Error("Connect the owner wallet first.");const me=await fetch("/api/profile/me").then(r=>r.json());if(!me.authenticated)await authenticateProfileSession({account:wallet,connect,signMessage,signProfileChallenge,onStatus:setStatus});}
  async function start(){setBusy(true);setAttempt(null);try{await ensureAuth();if(!tokenId||!targetId)throw new Error("Choose an owned Goon and a locked trick.");const response=await fetch("/api/trick-line/start",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({tokenId,targetTrickId:targetId})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRun(data);setTrickId(data.tricks[0].id);setObstacle(data.obstacles[0]);setStatus(`${data.mastery.entryCost} GRIT burned. Land two setup tricks, land ${data.target.name}, then bank.`);}catch(error){setStatus(error instanceof Error?error.message:"Unable to start mastery.");}finally{setBusy(false);}}
  async function act(){if(!run)return;setBusy(true);setAttempt(null);try{const required=run.session.sequence===2?run.target.id:trickId;const response=await fetch(`/api/trick-line/${run.session.id}/actions`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accessKey:run.accessKey,expectedSequence:run.session.sequence,trickId:required,stance:"regular",obstacle,mode:"standard",gritUsed:0})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRun(current=>current?{...current,session:data.session}:current);setAttempt(data.attempt);setStatus(data.attempt.landed?(data.session.sequence===3?"TARGET LANDED. Bank now for the mastery roll.":`SETUP ${data.session.sequence}/2 LANDED.`):"FALL. The entry cost is not refunded.");}catch(error){setStatus(error instanceof Error?error.message:"Attempt failed.");}finally{setBusy(false);}}
  async function bank(){if(!run)return;setBusy(true);try{const response=await fetch(`/api/trick-line/${run.session.id}/bank`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accessKey:run.accessKey,expectedSequence:run.session.sequence})});const data=await response.json();if(!response.ok)throw new Error(data.error);setRun(current=>current?{...current,session:data.session}:current);setStatus(data.mastery.unlocked?`MASTERED: ${run.target.name} is now in this Goon's permanent arsenal.`:data.mastery.qualified?`Qualified, but not unlocked. Pity odds increased by 10 points for the next run.`:"Line banked without qualifying. Pity odds did not change.");}catch(error){setStatus(error instanceof Error?error.message:"Could not bank line.");}finally{setBusy(false);}}

  const active=run?.session.status==="active";
  return <section className="trick-line-console" id="trick-line"><header><div><p className="eyebrow">TRAINING FACILITY // PAID MASTERY</p><h2>TRICK<br/><i>LINE</i></h2></div><p>Ranked matches earn GRIT. Mastery burns GRIT for a faster—but less reliable—path to advanced tricks. Sponsor milestones remain guaranteed.</p></header>
    {!active?<div className="trick-mastery-start"><label>OWNED GOON<select value={tokenId??""} onChange={e=>{setTokenId(Number(e.target.value)||null);setTargetId(null)}}><option value="">Choose your Goon</option>{owned.map(g=><option key={g.tokenId} value={g.tokenId}>#{String(g.tokenId).padStart(4,"0")} · {g.discipline} · {g.rarity}</option>)}</select></label>{selected&&<><div className="mastery-balance"><b>{spendable} GRIT SPENDABLE</b><span>{Number(economy.grit_reserved??0)} reserved</span></div><label>LOCKED TARGET<select value={targetId??""} onChange={e=>setTargetId(Number(e.target.value)||null)}><option value="">Choose a locked trick</option>{locked.map(t=><option key={t.id} value={t.id}>{t.name} · difficulty {t.difficulty}</option>)}</select></label>{target&&<div className="mastery-confirm"><b>{target.name}</b><span>Entry burns {target.difficulty<=6?3:target.difficulty<=8?5:8} GRIT</span><span>Current {spendable} → remaining {spendable-(target.difficulty<=6?3:target.difficulty<=8?5:8)}</span></div>}</>}<button className="button primary" onClick={start} disabled={busy||!target}>{account?busy?"STARTING…":"BURN GRIT + START":"CONNECT OWNER WALLET"}</button></div>
    :<div className="trick-line-live"><aside><Image src={run.goon.imageUrl} alt={run.goon.name} width={500} height={500}/><span>#{String(run.goon.tokenId).padStart(4,"0")} · {run.mastery.remainingGrit} GRIT LEFT</span></aside><div className="line-controls"><div className="mastery-target"><span>TARGET</span><b>{run.target.name}</b><small>{run.mastery.chance}% unlock chance · guarantee by qualified run {run.mastery.guaranteeRun}</small></div><div className="line-score"><span>SETUPS LANDED<b>{Math.min(2,run.session.landedCount)} / 2</b></span><span>ENTRY BURNED<b>{run.session.entryCost} GRIT</b></span><span>STAGE<b>{run.session.sequence<2?"SETUP":run.session.sequence===2?"TARGET":"BANK"}</b></span></div>{run.session.sequence<2&&<label>SETUP TRICK<select value={trickId} onChange={e=>setTrickId(Number(e.target.value))}>{run.tricks.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}<label>OBSTACLE<select value={obstacle} onChange={e=>setObstacle(e.target.value)}>{run.obstacles.map(o=><option key={o}>{o}</option>)}</select></label><div className="line-actions"><button onClick={act} disabled={busy||run.session.sequence>=3}>{run.session.sequence===2?`TRY ${run.target.name.toUpperCase()}`:"TRY SETUP TRICK"}</button><button onClick={bank} disabled={busy||run.session.sequence!==3}>BANK + ROLL MASTERY</button></div>{attempt&&<div className={`line-outcome ${attempt.landed?"landed":"fell"}`}><b>{attempt.landed?"LANDED":"FALL"}</b><span>{attempt.trick} · {attempt.chance}% chance · roll {attempt.roll}</span></div>}</div></div>}
    <p className="trick-line-status" aria-live="polite">{status}</p></section>;
}
